### ISSUE TITLE
mvn clean install fails

### ISSUE THREAD

**Issue by ghillairet** [neo4j-contrib/neo4j-osgi#5]
I follow the build steps in README, but mvn clean install on neo4j-osgi fails with following error:

$ mvn clean install
[INFO] Scanning for projects...
Downloading: http://repo1.maven.org/maven2/org/neo4j/build/parent-pom/29/parent-pom-29.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project org.neo4j.build:osgi-build:0.1-SNAPSHOT (/Users/guillaume/Projects/neo4j-osgi/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.neo4j.build:parent-pom:pom:29 in central (http://repo1.maven.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 3, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by ghillairet** [comment]
I fixed it by modifying the artifactId of the parent in pom.xml by community.build

```
<parent>
    <groupId>org.neo4j.build</groupId>
    <artifactId>community-build</artifactId>
    <version>1.6.M02</version>
  </parent>
```

**Comment by nawroth** [comment]
The proper fix is to add this repo to the build: http://m2.neo4j.org/releases

**Comment by ghillairet** [comment]
Thanks, this works perfectly.
